### ISSUE TITLE
Switch to official php image and php 7

### ISSUE THREAD

**Issue by ujovlado** [keboola/db-extractor-pgsql#16]

**Comment by pivnicek** [comment]
This was done a long time ago

**Comment by pivnicek** [comment]
no it wasn't, liar.

**Comment by pivnicek** [comment]
how did I have an old version of this locally?  ugh

**Comment by ujovlado** [comment]
what a mess :)

**Comment by pivnicek** [comment]
php storm had this ancient version in my "recent projects" list and it took me a little bit to figure out what the hell was up:)
