### ISSUE TITLE
Update to latest standards

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-pgsql#23]
This issue will cover multiple PRs
- [x] new CI / latest php
- [x] keboola coding standards
- [x] db-extractor-common 9.*
- [x] json configurations
The above is covered by https://github.com/keboola/db-extractor-pgsql/pull/29
- [x] row configurations
- [ ] datadir testing

**Comment by odinuv** [comment]
that would also fix connection retry 
https://keboola.zendesk.com/agent/tickets/9021

**Comment by pivnicek** [comment]
Yes, I've just made a new branch for this, going to give it the update 👍

**Comment by pivnicek** [comment]
Still needs datadir tests and configRow support

**Comment by odinuv** [comment]
can't that be separate?

**Comment by pivnicek** [comment]
Closing this now that config-row support is done #46
