### ISSUE TITLE
Gettables SQL error - unnest not supported in pgsql < 8.4

### ISSUE THREAD

**Issue by pivnicek** [keboola/db-extractor-pgsql#35]
SQLSTATE[42883]: Undefined function: 7 ERROR:  function unnest(smallint[]) does not exist LINE 23:                   unnest(conkey) AS conkey, unnest(confkey) ...                            ^ HINT:  No function matches the given name and argument types. You may need to add explicit type casts.

thrown on https://github.com/keboola/db-extractor-pgsql/blob/master/src/Keboola/DbExtractor/Extractor/PgSQL.php#L362

**Comment by pivnicek** [comment]
The problem line is https://github.com/keboola/db-extractor-pgsql/blob/master/src/Keboola/DbExtractor/Extractor/PgSQL.php#L323

**Comment by pivnicek** [comment]
`unnest` appears to be supported from pgsql 8.4 onwards

**Comment by Halama** [comment]
The version of pgsql which was failing is `PostgreSQL 8.2.14 on i686-redhat-linux-gnu, compiled by GCC gcc (GCC) 4.1.2 20070626 (Red Hat 4.1.2-14)`

Reference https://keboola.zendesk.com/agent/tickets/9366

**Comment by Halama** [comment]
Final release 2011 https://www.postgresql.org/support/versioning/

**Comment by Halama** [comment]
I think we shouldn't support these ancient releases especially if it requires some special conditions or non-optimal performance for others in extractor.
But what to do with them?

**Comment by pivnicek** [comment]
yes, I agree, we should actively encourage our users to keep their software up to date.  

One thing that could help with this is if they could run on an old tag until they update their DB.
https://github.com/keboola/orchestrator-bundle/issues/77
The extractor can recognize that the db-server version is unsupported and warn in the UI.

A similar situation may occur in the future with sql server 2008

**Comment by Halama** [comment]
Is there some workaround for this issue without hacks and performance side effects?

**Comment by pivnicek** [comment]
yes, we can exclude that whole section tbh, 
```
LEFT JOIN (
      SELECT conname AS constraint_name, conrelid AS con_table_oid, ta.attname AS con_column_name, 
      ta.attnum AS con_ordinal, confrelid::regclass AS foreign_table_name, fa.attname AS foreign_column_name
          FROM (
           SELECT conname, conrelid, confrelid,
                  unnest(conkey) AS conkey, unnest(confkey) AS confkey
             FROM pg_constraint
            WHERE contype = 'f'
          ) sub
          JOIN pg_attribute AS ta ON ta.attrelid = conrelid AND ta.attnum = conkey
          JOIN pg_attribute AS fa ON fa.attrelid = confrelid AND fa.attnum = confkey
    ) fks ON (a.attrelid, a.attnum) = (con_table_oid, con_ordinal) -- foriegn keys
```
it is only used to check FKs which we aren't using in the frontend yet anyhow.
