### ISSUE TITLE
"Bad" column name as an app error

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-pgsql#45]
Error message example: `The column \"in.c-keboola-ex-db-pgsql-5753940.samples.rate%\" was not found.`

https://keboola.slack.com/archives/C09U3R1J4/p1546424107017800

Related to https://github.com/keboola/db-extractor-mssql/issues/25 and https://github.com/keboola/db-extractor-common/issues/38

**Comment by pivnicek** [comment]
hmm, this is strange.  the request goes to `Client->request('post', 'v2/storage/columns/in.c-keboola-ex-db-pgsql-5753940.materials.VAT_RATE/metadata'` which should be correct, I don't know yet where this % is coming from

**Comment by Halama** [comment]
Maybe I did wrong debug. Today it happened on mssql ex https://keboola.slack.com/archives/C09U3R1J4/p1546508648020100
I am going to check it

**Comment by Halama** [comment]
ok I think it is related to parallel imports:(

**Comment by Halama** [comment]
I'll move it to proper repository

**Comment by Halama** [comment]
second issue will be that strange `%` on the end.

**Comment by Halama** [comment]
I am going to simulate it now

**Comment by Halama** [comment]
I am closing it here. Sorry for misleading issue.
