### ISSUE TITLE
Failed to get tables internal error

### ISSUE THREAD

**Issue by Halama** [keboola/db-extractor-pgsql#63]
https://connection.keboola.com/admin/utils/logs?file=2019/04/24/03/2019-04-24-03-03-46-5cbfb5f218c4f-exception

`...  AND ns.nspname NOT LIKE 'pg_toast%'       AND ns.nspname NOT LIKE 'pg_temp%' AND c.relname IN ('sh_exrozdiad') AND ns.nspname IN ('public') ERROR:  syntax error at or near \"*\" LINE 1: ...'public' ) ) TO STDOUT WITH CSV DELIMITER ',' FORCE `

https://keboola.slack.com/archives/C09U3R1J4/p1556067885031900

**Comment by Halama** [comment]
Isn't it related to this change https://github.com/keboola/db-extractor-pgsql/pull/62 ?

**Comment by pivnicek** [comment]
possibly

**Comment by Halama** [comment]
https://papertrailapp.com/groups/23635/events?q="Error%20using%20copy%20command"

**Comment by pivnicek** [comment]
I put it back to `2.5.2` while I investigate.  Will see if it's best to rollback or fix.

**Comment by pivnicek** [comment]
I'm wondering if this may be dependent on postgres version.
