### ISSUE TITLE
Cannot get list of tables

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/db-extractor-pgsql#73]
After #66 this is broken. 

```
An error occurred while fetching the list of tables
Unrecognized option "tables" under "parameters"
```

@odinuv prosimtě, s #66 nefunguje sync akce getTables. Asi tomu chybí buď ignore extra values nebo by to mělo mít všechno, co podporoval ten původní config... (https://github.com/keboola/db-extractor-pgsql/pull/66/files#r285050148)

UIčko to volá takhle:
```
{"parameters":{"db":{"port":XXX,"ssh":{"sshPort":22},"host":"xxxx","#password":"xxx","user":"xxx","database":"xxxx"},"tables":[]}}
```

Ref.: https://keboola.zendesk.com/agent/tickets/10897

**Comment by pivnicek** [comment]
treba mame to vyresit v uicko?

**Comment by odinuv** [comment]
pokud to neni bug v UI, tak bych tam dal ignore extra keys
ale trosku podezrivam bug v UI ze se to objevilo po 2 mesicich

**Comment by pivnicek** [comment]
souhlasim, I vote that we move it there.

**Comment by pivnicek** [comment]
I believe that the `tables` comes from here: https://github.com/keboola/kbc-ui/commit/9c966f145c670de3ff36403071f3e75360728474#diff-3af743b540daae7adcf188f198b402faR523

So we should add `ignore extra keys` imho

**Comment by pivnicek** [comment]
non-configRow configs have `tables[]` under parameters.

**Comment by odinuv** [comment]
ok, let's add ignore extra keys so as not to put strain on the UI

**Comment by pivnicek** [comment]
I'll take care of it @odinuv , no worries.

**Comment by odinuv** [comment]
thx a lot!
