### ISSUE TITLE
Update test DB

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/db-extractor-pgsql#75]
Mail from AWS: 

>Hello,
>
>Our records indicate that you have one or more RDS for PostgreSQL instances running version 10 or 11, or Aurora PostgreSQL instances compatible with PostgreSQL 10.
>
>The PostgreSQL community has updated [1] their open source database versions 10 and 11 to address a security issue [2]. If the PostgreSQL instance is not updated, then it could be crashed or made to run unauthorized code with specially crafted network traffic generated by an authorized user. 
>
>Amazon RDS for PostgreSQL and Amazon Aurora with PostgreSQL compatibility are based on open source PostgreSQL and provide a managed database service where each database instance runs on its own dedicated EC2 instance. No clients can access these databases other than those explicitly permitted for that instance by the customer.
>
>Amazon RDS has released new minor versions of PostgreSQL 10.9 and 11.4, which contain updates that address this security issue. Customers with existing PostgreSQL instances using versions 10 and 11 should upgrade [3] to the respective minor versions 10.9 and 11.4. 
>
>Amazon Aurora has released a patched version of Aurora PostgreSQL, version 2.3.3 (compatible with PostgreSQL 10.7) which contains updates that address this security issue. Customers running older versions of Aurora PostgreSQL version 2 (compatible with PostgreSQL 10) should upgrade [4] to this patched release (version 2.3.3).
>
>Your unpatched database instances in the US-EAST-1 Region are listed below:
>testing-ex-db-pgsql
>
>
>To learn more about upgrading minor versions in Amazon RDS, review Upgrading Database Engine Versions [3] [4].
>
>For more information about this security advisory, please see [1]. For more information about managing secure network access to Amazon RDS instances, please see Controlling Access with security groups [5]. For more information about Amazon Aurora security, please see Security with Amazon Aurora PostgreSQL [6] .
>
>Should you have any questions or concerns, the AWS Support Team is available on the community forums and via AWS Premium Support [7].
>
>[1] https://www.postgresql.org/about/news/1949/
>[2] https://cve.mitre.org/cgi-bin/cvename.cgi?name=2019-10164
>[3] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_UpgradeDBInstance.PostgreSQL.html
>[4] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Updates.html
>[5] https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.RDSSecurityGroups.html
>[6] https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Security.html
>[7] https://aws.amazon.com/support
>
>Sincerely,
>Amazon Web Services
>
>Amazon Web Services, Inc. is a subsidiary of Amazon.com, Inc. Amazon.com is a registered trademark of Amazon.com, Inc. This message was produced and distributed by Amazon Web Services Inc., 410 Terry Ave. North, Seattle, WA 98109-5210

**Comment by pivnicek** [comment]
updated, thanks for the issue
